datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      image_path: /home/lbh/Dataset/Emotion/mer2023/video

      ann_path: /home/user/selected_face/face_emotion/relative_train_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_coarse_grained.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_fine_grained.txt
